### ISSUE TITLE
关于HttpClient类的一个建议

### ISSUE THREAD

**Issue by liamksmith** [iEternity/HttpClient#1]
1. httpClient类其实是不用做成单例的，用完释放就好了。现在的设计没有办法用于需要同时有多个会话存在的场景。
2. HttpRequest的setUrl(&&)、setTag(&&)、setCallback(&&)这几个函数似乎没有用到。
3. 我看到有多个地方返回了string.data()，如下

```
const char* getUrl() const
	{
		return url_.data();
	}
```
,我建议如果string对象里放的是二进制数据用data,如果放的是以\0结尾的字符串用c_str，这样代码看上去会更清晰一些。

4. HttpClient类的send和sendImmediate可以合并掉，用一个参数区分一下是不是立即发送。

5.`const HttpCookie* getCookie() const { return cookie_; } `返回内部的指针不安全，即使是const也可能被强制转化去掉限制，不如直接返回一个HttpCookie对象。

**Comment by iEternity** [comment]
（1）应该不存在你说的这个问题，因为你发送请求时实际上回将这个请求放到线程池的队列中，然后执行doPost()、doGet()等方法，在这个函数中会创建一个栈上的Curl对象用来执行实际的Http请求，HttpClient并没有直接发送请求。
（2）当你传递右值参数的时候会优先匹配到右值版的函数，可以减少一次拷贝构造。
（3）在c++11中的data() 和c_str()没有任何区别，string一般都是用来存放字符串的吧，我只是更习惯使用data()函数^-^。
（4）你的建议挺好的，属于API风格不同。
（5）因为HttpCookie是一个大对象，直接返回对象的话会有拷贝的开销，返回对象的引用也是可以的，但是调用者很容易没有使用HttpCookie& 来接收返回值，又会增加拷贝的开销。所以干脆就返回指针了。

**Comment by liamksmith** [comment]
重新看了一下那个单例确实是没有影响，是之前没有看清楚。
